### ISSUE TITLE
Get feature files from open source repositories

### ISSUE THREAD

**Issue by sponte** [oss-specs/specs#21]
This is about being able to view your specs from github.com, gitlab.com etc. We would scan and display repo's contents

**Comment by jimCresswell** [comment]
So you feed a URL to an instance of specsExpress (Specs?) and it gives you back a URL at which you can view the pretified, searchable specs?

**Comment by jimCresswell** [comment]
I think this falls under basic functionality so adding it to the alpha milestone.

**Comment by jimCresswell** [comment]
Given the repo, get a list of files
* Github.com: https://developer.github.com/v3/git/trees/#get-a-tree
* Gitlab.com: http://doc.gitlab.com/ce/api/repositories.html#list-repository-tree
* Bitbucket.com: not supported https://bitbucket.org/site/master/issue/8316/rest-api-list-all-files-in-repo-like-git .

Given the repo search for files
 * Github.com: https://developer.github.com/v3/search/#search-code e.g. https://api.github.com/search/code?q=feature+repo:oss-specs/specs+extension:feature

Given the repo, get an archive of the repo
* Github.com: https://developer.github.com/v3/repos/contents/#get-archive-link
* Gitlab.com: http://doc.gitlab.com/ce/api/repositories.html#get-file-archive
* Bitbucket.com: does not appear to be supported.

**Comment by jimCresswell** [comment]
@orangeMug this is a little service to grab Gherkin feature files from a repo and expose them in a web UI. The primary aim is to make in-repo specifications visible to people who don't know how, or don't want, to use services like e.g. Gitlab. Secondary functionality will include allowing specifications to be searched, filtered etc.

I was just thinking about how to pull the feature files out of the repos. Host APIs (Github, Gitlab) allow files to be found then downloaded, or the whole repo to be grabbed as an archive. Alternatively, dependencies on APIs could be done away with by checking out the whole repo with Git - causing quite a lot of unnecessary network and disk IO. If you have any thoughts I would appreciate hearing them, if not that is fine too :smile:

**Comment by orangemug** [comment]
Git seems pretty standard these days, so it makes sense to me to use git so you have a single standard API to all the services you may want to support in future. You can use a shallow clone to cut down on data transfer (http://stackoverflow.com/questions/6941889/is-git-clone-depth-1-shallow-clone-more-useful-than-it-makes-out)

However you'll probably also want to support different branches (develop / master), rather than just HEAD. There is some info over here http://stackoverflow.com/questions/3489173/how-to-clone-git-repository-with-specific-revision-changeset but from the comments I'm not sure it works...

I wonder if @pornel would be so kind as to pass on his ninja git skills :)

**Comment by pornel** [comment]
I'm not sure what you're trying to do, but `git ls-remote $url` will list branches and tags, and `git clone $url --depth=1 -b $branch` will clone just one commit, so you can search the files.

**Comment by jimCresswell** [comment]
@orangemug @pornel thanks guys! The idea is to get `.feature` files containing specs out of a repo and display them in a nice web interface so that e.g. business analysts can look at them without knowing what GitHub or GitLab is.

**Comment by jimCresswell** [comment]
A basic version of this is done using node-git.
